[build]
  command = "npx prisma generate && npx prisma db push --skip-generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.0.0"
  DATABASE_URL = "file:./dev.db"

[[plugins]]
  package = "@netlify/plugin-nextjs"
